### ISSUE TITLE
review - 1

### ISSUE THREAD

**Issue by thammegowda** [avindsilva/SpiralMatrix#1]
- **Generated Files are committed** : There is no need to add generated files to git repository as they can be generated any time we want. By generated files, I meant the ***.class** files. So exclude the *.class files. Have you come across **.gitignore**?, if not, please explore https://help.github.com/articles/ignoring-files/
- **Java Code Conventions are violated** : Well, you have followed the conventions to best effort, but there are few issues  regarding spaces. Revisit section `8.2` in [Code Conventions](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf) (I recommend you to revise this whole guide) 
- **Doc Scrings are missing** : Classes and methods do not have documentation. Revise section `5.2` of [Code Conventions](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf)
- **No README file** : It is a best practice to include a `README` file in the root directory and describe what this project is about, how to compile and run your code.

**Comment by avindsilva** [comment]
Resolved this issue with the below commit id 
1debe22a35b9890b8936ae6ddc8b735330875546

**Comment by thammegowda** [comment]
Well Done! :+1: 
More feed back :
- Improvement :  the `.class` files are still present in the HEAD of the branch. You can remove already tracked `.class` files using `git rm`. [Read More](http://stackoverflow.com/a/2047477/1506477)
